<?php
/**
 * Affiche la liste des documents proposés en ligne
 *
 *
 * @project pits
 * @package application/views/scripts/admin
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 8 mars 2011
 * @version $Id: $
 */
$this->retour = $this->link('admin', 'index');
$this->helpadd = $this->link('admin', 'helpadd')
?>
<h2>Documentation</h2>
<?php
echo $this->partial('common/listedocs.phtml', array('liste' => $this->liste, 'docPath' => $this->docPath, 'btnSuppr' => true, 'btnclass' => 'field_btn_contact'));
echo $this->makeButton('cancel', 'cancel', $this->retour, 'Retour', 'field_btn_contact', 'margin-left: 80px;');
echo $this->makeButton('ajout', 'ajout', $this->helpadd, 'Nouveau document', 'field_btn_contact', 'margin-left: 80px;');
?>
