<?php
/**
* Vue permettant d'ajouter un arrêt sur un circuit
* 
* @project pits
* @package application/views/scripts/admin
* @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
* @date 23 juin 2011
* @version $Id: $
*/

?>
<h1>Administration des inscriptions aux transports scolaires</h1>
<h2>Ajout d'un arrêt sur le circuit <?php echo $this->CodeService; ?></h2>
<?php echo $this->form; ?>
