<?php
/**
* Confirmation de la suppression du compte d'un user
* 
* @project pits
* @package application/views/scripts/admin
* @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
* @date 8 mars 2011
* @version $Id: $
*/

?>
<h1>Administration des inscriptions aux transports scolaires</h1>
<h2>Suppression d'un utilisateur</h2>
<p class="description">Vous souhaitez supprimer le compte de <?php echo $this->user->Nom . ' ' . $this->user->Prenom; ?>.</p>
<?php echo $this->form; ?>