<?php
/**
 * Impose un mot de passe à un administrateur
 *
 * Le mot de passe est tapé en clair
 *
 * @project pits
 * @package appplication/views/scripts/sadmin
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 7 mars 2011
 * @version $Id: $
 */

?>
<h1>Configuration des inscriptions aux transports scolaires</h1>
<h3>Nouveau mot de passe</h3>
<?php echo $this->form;?>
