<?php
/**
 * Vider le fichier Log après téléchargement pour sauvegarde
 *
 * Affiche le contenu du fichier log dans un TEXTAREA en lecture seule
 *
 * @project pits
 * @package appplication/views/scripts/sadmin
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 mars 2011
 * @version $Id: $
 */

?>
<h1>Configuration des inscriptions aux transports scolaires</h1>
<h2>Gestion du fichier Log</h2>
<?php echo $this->form;?>
