<?php
/**
 * Vider la table des utilisateurs
 *
 * 2 boutons : vider ou abandonner
 *
 * @project pits
 * @package appplication/views/scripts/sadmin
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 7 mars 2011
 * @version $Id: $
 */

?>
<h1>Configuration des inscriptions aux transports scolaires</h1>
<h2>Préparation d'une année scolaire</h2>
<h3>Vider la table des utilisateurs</h3>
<?php
if ($this->err) {
    echo '<p class="description">' . $this->msg . '</p>';
    echo $this->makeButton('suite', 'suite', $this->link('sadmin', 'index'), 'Continuer', 'field_btn_contact');
} else {
    echo $this->form;
}
?>
