<?php
/**
 * Page d'accueil de l'espace du super administrateur
 *
 * @project télé-paiement CCM
 * @package application/views/scripts/sadmin
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 8 sept. 2011
 * @version $Id: $
 */

?>
<h1>Espace du super administrateur</h1>
<div class="user">
	<table class="user">
		<tbody>
			<tr>
				<td><a id="pageindex"
					href="<?php echo $this->link('admin', 'index'); ?>">Espace
						administrateur</a></td>
				<td><a id="pageindex"
					href="<?php echo $this->link('user', 'index'); ?>">Espace
						utilisateur</a></td>
			</tr>
		</tbody>
	</table>
</div>
