<h1><?php echo $this->escape($this->pageTitle); ?></h1>
<table align="center" cellpadding="5" cellspacing="1">
	<tbody>
		<tr>
			<td>
			<h3>Critère d'extraction des fiches</h3>
			<p>Le formulaire est initialisé avec la date de la dernière extraction.<br/> Tous les élèves inscrits ou modifiés à partir de cette date seront
			extraits.</p>
			<?php echo $this->form; ?></td>
		</tr>
	</tbody>
</table>
'
