<div id="piedpage" class="fondpiedpage"> 
  <br /> 
  <div class="module">
    <a href="http://www.cc-montesquieu.fr/v2/index.php/component/option,com_sitemap/Itemid,864/" class="mainlevel" title="Plan du site" >Plan du site</a>
    <a href="http://www.cc-montesquieu.fr/v2/index.php/component/option,com_contact/Itemid,863/" class="mainlevel" title="Contacter les services de la CCM" >Contact</a> 
    <a href="http://www.cc-montesquieu.fr/v2/index.php/content/view/668/765/" class="mainlevel" title="Mentions légales" >Mentions légales</a> 
  </div> 
  <div class="modulecoords"> 
     <div align="right">
       &copy; 2010 Communaut&eacute; de Communes de Montesquieu - tous droits r&eacute;serv&eacute;s
     </div>
  </div> 
</div>   
