<?php
/**
 * Affiche une liste de documents
 *
 * @project télé-paiement CCM
 * @package application/views/script/common
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 5 mars 2011 - rev.20/09/2011
 * @version $Id: $
 */
?>
<div align="center" class="tp">
<?php if (count($this->liste) == 0) : ?>
	<h3>Il n'y a pas de document disponible</h3>
<?php else : ?>
	<h3>Téléchargez les documents</h3>
	<table class="tp">
		<thead>
			<tr>
				<th>Liste des documents</th>
				<?php if (isset($this->btnSuppr)) :?>
				<th></th>
				<?php endif; ?>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($this->liste as $document) : ?>
			<tr>
				<td><a href="<?php echo $this->docPath . DIRECTORY_SEPARATOR . $document; ?>" class="listedoc"><?php echo $document; ?>
				</a></td>
				<?php if (isset($this->btnSuppr)) : ?>
				<?php  $btnclass = isset($this->btnclass) ? $this->btnclass: array('button' => 'btnliste', 'a' => 'sansdeco'); ?>
				<td><?php echo $this->makeButton('suppr', 'suppr', $this->link('admin', 'helpsuppr', null, array('d' => $document,)), 'Supprimer', $btnclass); ?>
				</td>
				<?php endif; ?>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php endif; ?>
</div>