<?php
/**
* Description courte du fichier
*
* Description longue du fichier s'il y en a une
* 
* @project pits
* @package package_name
* @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
* @date 17 juin 2011
* @version $Id: $
*/

?>
<h1>Mise à jour des bases</h1>
<table class="pits_index_sadmin">
				<tbody class="pits_menu_sadmin">
					<tr>
						<td width="100%"><a id="pageindex"
							href="<?php echo $this->link('sadmin', 'index'); ?>">Espace
								sadmin</a></td>
					</tr>
					<tr>
						<td>&nbsp;</td>
					</tr>
				</tbody>
				<tbody>
					<tr>
						<td><a id="pageindex"
							href="<?php echo $this->link('maj', 'services'); ?>">Mise à jour des
								services</a></td>
					</tr>
				</tbody>
			</table>