<?php 
/**
 * Indique la version du logiciel et la version de Zend Framework
 */
?>
<h1>Version</h1>
<table align="center" cellpadding="5" cellspacing="1">
	<tbody>
		<tr><td>pits</td><td><?php echo $this->pits; ?></td></tr>
		<tr><td>zf</td><td><?php echo $this->zend; ?></td></tr>
	</tbody>
</table>
<div style="text-align:center; font-size: 10px;">
Réalisation DAFAP Informatique - dafap@free.fr - tél. 06 07 87 94 44
</div>