<?php
/**
 * Demande une validation pour désinscrire tous les élèves
 *
 * Description longue du fichier s'il y en a une
 *
 * @project PiTS CCM
 * @package application/views/scripts/sadmin
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 6 mars 2012
 * @version $Id: $
 */

?>
<p>&nbsp;</p>
<table align="center" cellpadding="5" cellspacing="1">
<tbody>
<tr>
<td>
<h3>Préparation d'une nouvelle année scolaire</h3>
<p>Vous avez demandé de passer tous les élèves à l'état de <b>non inscrits</b>.</p>
<p>Cette procédure annuelle est irréversible et ne doit être lancée qu'au moment de la préparation de la nouvelle année scolaire.</p>
<p>Confirmez-vous ?</p>
<?php echo $this->form; ?>
</td>
</tr>
</tbody>
</table>
