<?php
/**
 * Description courte du fichier
 *
 * Description longue du fichier s'il y en a une
 *
 * @project project_name
 * @package package_name
 * @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
 * @date 19 mars 2012
 * @version $Id: $
 */

echo '<p>&nbsp;</p>';
echo '<table align="center" cellpadding="5" cellspacing="1">
<tbody>
<tr>
<td>
<h3>Suppression des utilisateurs inactifs depuis plus d\'un an et 4 mois</h3>';
if ($this->phase == 2) {
    echo '<p>' . $this->result['user'] . ' utilisateurs supprimés</p>';
    echo '<p>' . $this->result['eleves'] . ' enfants supprimés</p>';
    echo $this->makeButton('suite', 'suite', $this->link('sadmin', 'index'), 'Continuer', 'btnliste', 'float:right;');
} else {
    echo '<p>Vous avez demandé de supprimer tous les utilisateurs qui ne se sont pas connectés depuis au moins 1 an et 4 mois.</p>';
    echo '<p>Cette procédure annuelle est irréversible et ne doit être lancée qu\'au moment de la préparation de la nouvelle année scolaire.</p>';
    echo '<p>Les enfants de ces utilisateurs seront également supprimés.';
    echo '<p>Confirmez-vous ?</p>';
    echo $this->form;
}
echo '</td>
</tr>
</tbody>
</table>';