<?php
/**
* Description courte du fichier
*
* Description longue du fichier s'il y en a une
* 
* @project project_name
* @package package_name
* @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
* @date 11 oct. 2011
* @version $Id: $
*/

?>
<h1>Test d'entrée</h1>
<table class="user">
<tbody>
<tr>
<td>
Email : <?php echo $this->Email;?>
</td>
<td>
Contrôle : <?php echo $this->ctrl; ?>
</td>
</tr>
</tbody>
</table>