<?php
/**
* Description courte du fichier
*
* Description longue du fichier s'il y en a une
* 
* @project pits
* @package package_name
* @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
* @date 8 mai 2011
* @version $Id: $
*/

?>
<div class="footer">
  <div class="contener_wf">
  Réalisation 
  <a href="http://dafap.free.fr" target="_blank">Dafap informatique</a>
  &amp; Hébergement Agence internet
  <a href="http://www.webfutur.com" target="_blank">Webfutur.com</a>
  </div>
  <div class="contener_mention_plan">
  &copy;2011 COBAS - 
  <a href="#" class="txt9_ffffff">Mentions légales</a>
  -
  <a href="#" class="txt9_ffffff">Plan du site</a>
  </div>
</div>