<?php if ($this->pageCount): ?>
<div class="paginationControl">
	<!-- First page link -->
	<?php if (isset($this->previous)): ?>
	<a href="<?php echo $this->url(array('page' => $this->first)); ?>">
		&lt;&lt; </a> |
		<?php else: ?>
	<span class="current"><?php echo $this->translate('premier'); ?></span> |
	<?php endif; ?>

	<!-- Previous page link -->
	<?php if (isset($this->previous)): ?>
	<a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
	<?php echo $this->translate("précédent"); ?> </a> |
	<?php else: ?>
	<span class="disabled"><?php echo $this->translate("précédent"); ?>
	</span> |
	<?php endif; ?>

	<!-- Numbered page links -->
	<?php foreach ($this->pagesInRange as $page): ?>
	<?php if ($page != $this->current): ?>
	<a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?>
	</a> |
	<?php else: ?>
	<span class="current"><?php echo $page; ?> </span> |
	<?php endif; ?>
	<?php endforeach; ?>

	<!-- Next page link -->
	<?php if (isset($this->next)): ?>
	<a href="<?php echo $this->url(array('page' => $this->next)); ?>"><?php echo $this->translate("suivant"); ?>
		</a>
		<?php else: ?>
	<span class="disabled"><?php echo $this->translate("suivant"); ?></span>
	<?php endif; ?>
	
	<!-- Last page link -->
	<?php if (isset($this->next)): ?>
	| <a href="<?php echo $this->url(array('page' => $this->last)); ?>">
		&gt;&gt; </a>
		<?php else: ?>
	| <span class="current"><?php echo $this->translate('dernier'); ?></span> 
	<?php endif; ?>
	
</div>
	<?php endif; ?>