<?php
/**
* Valider et payer l'ensemble des prestations demandées
*
* Description longue du fichier s'il y en a une
* 
* @project pits
* @package application/views/scripts/parent
* @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
* @date 13 mai 2011
* @version $Id: $
*/

?>
<h1>Inscription aux transports scolaires</h1>
<h2>Valider les demandes d'inscription et payer les prestations demandées</h2>
<p>content: <?php echo $this->content; ?></p>
<p>N° err: <?php echo $this->err; ?></p>
<p>Msg err: <?php echo $this->errmsg; ?></p>
<p><?php Zend_Debug::dump($this->header, 'infos'); ?></p>
