<?php
/**
* Suppression d'un élève
*
* Description longue du fichier s'il y en a une
* 
* @project pits
* @package application/views/scripts/parent
* @author DAFAP Informatique - Alain Pomirol (dafap@free.fr)
* @date 13 mai 2011
* @version $Id: $
*/

?>
<h1>Inscription aux transports scolaires</h1>
<h2>Suppression d'un élève</h2>
<p class="description">Vous avez demandé la suppression de l'inscrition de <?php echo $this->eleve->Nom . ' ' . $this->eleve->Prenom; ?>.</p>
<?php echo $this->form; ?>